
INSERT INTO roles(name) VALUES ('ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES ('TRANSPORTISTA') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES ('AGENTE') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES ('AUDITOR') ON CONFLICT DO NOTHING;
